batch_size: 8
coord_dim: 3
data_folder: Data/spheres_HF_data
dimension: 2
distance_columns:
- distanceToSurface
distance_dim: 1
dropout: 0.3
hidden_size: 128
lhs_sample: 500000
loss_type: mse
low_fi_data_folder: Data/spheres_LF_data
low_fi_dropout: 0.0
lr: 0.0001
lr_gamma: 1.5
model_type: low_fi_fusion
num_epochs: 2
num_hidden_layers: 3
output_dim: 6
param_columns:
- x_field
- y_field
- Mach_field
param_dim: 3
print_every: 1
project_name: orion_hyperparam_sweep_0
shuffle: false
test_size: 0.2
