batch_size: 8
coord_dim: 3
data_folder: Data/x_43_data_36
dimension: 2
distance_columns:
- distanceToSurface
distance_dim: 1
hidden_size: 128
lhs_sample: 500000
loss_type: mse
low_fi_data_folder: Data/x_43_data_36
lr: 0.001
lr_gamma: 1.2
model_type: low_fi_fusion
num_epochs: 50000
num_hidden_layers: 5
output_dim: 6
param_columns:
- a2
- a3
- a4
param_dim: 3
print_every: 1
project_name: double_hf_small
shuffle: true
test_size: 0.2
dist_threshold: .01
edge_percentile: .001
x_lim: [-1, 5]
y_lim: [-2, 2]
